### ISSUE TITLE
Добавить возможность Share post

### ISSUE THREAD

**Issue by aibolik** [datbayev/whyit#3]
Думаю было бы полезно добавить Twitter, Facebook и другие интеграции, чтобы можно было пост зашейрить.

Будет какой-то органический трафик.

**Comment by datbayev** [comment]
@aibolik, ты об этом?

<img width="1022" alt="screen shot 2017-07-27 at 12 39 23" src="https://user-images.githubusercontent.com/457089/28657386-b585a8fc-72c8-11e7-9a5c-ec2089e46184.png">

Но конечно же кнопочки можно улучшить, показывать счетчики с количеством шейров. Please feel free to add this functionality :)

**Comment by datbayev** [comment]
@aibolik ?

**Comment by aibolik** [comment]
Да. Первый раз когда делился не заметил. Так что этот Issue лучше закрыть
